cul-it/qa_server

- app/assets/stylesheets/application.css
- app/controllers/authority_status_controller.rb
- app/views/authority_status/index.html.erb
- app/views/homepage/index.html.erb
- config/authorities/linked_data/nalt_cornell.json
- config/locales/en.yml
Also fixes problems with NALT authority configuration.  All authorities are now green.
> Allow user to get the staus of a selected authority or all authorities

- app/controllers/authority_status_controller.rb
- config/authorities/linked_data/geonames_ld4l_cache.json
> Extend geonames config to support entities corresponding to gn:featureClass

- app/assets/stylesheets/application.css
- app/controllers/authority_validation_controller.rb
- app/controllers/check_status_controller.rb
- app/loggers/scenario_logger.rb
- app/models/search_scenario.rb
- app/presenters/check_status_presenter.rb
- app/presenters/monitor_status_presenter.rb
- app/services/authority_validator_service.rb
- app/validators/scenario_validator.rb
- app/validators/search_scenario_validator.rb
- app/validators/term_scenario_validator.rb
- app/views/authority_list/index.html.erb
- app/views/check_status/index.html.erb
- app/views/homepage/index.html.erb
- app/views/layouts/application.html.erb
- app/views/monitor_status/index.html.erb
- app/views/usage/index.html.erb
- config/authorities/linked_data/scenarios/locgenres_ld4l_cache_validation.yml
- config/locales/en.yml
* existing scenarios are categorized as connection validations
* scenarios that compare an actual result with an expected result are accuracy tests
* added accuracy tests for LoC Genre/Form
* minor style cleanup to prefer `-` over `_`
> add support for validation types

- Gemfile.lock
* adds support for terms to be fetched as `application/ld+json`
> update qa min_context

- Gemfile
- Gemfile.lock
> update qa_server to 1.2.2

- Gemfile
- Gemfile.lock
- config/initializers/qa.rb
- public/qa/apidoc/apidoc.json
> Update to qa_server 1.2.2

- config/authorities/linked_data/locnames_ld4l_cache.json
- config/authorities/linked_data/scenarios/locdemographics_ld4l_cache_validation.yml
* add accuracy tests for demographics
* change locnames to use skos:prefLabel instead of madsrdf:authoritativeLabel
> update authority configurations

- config/authorities/linked_data/DISABLED/agrovoc_direct.json
- config/authorities/linked_data/agrovoc_ld4l_cache.json
- config/authorities/linked_data/dbpedia_ld4l_cache.json
- config/authorities/linked_data/geonames_direct.json
- config/authorities/linked_data/geonames_ld4l_cache.json
- config/authorities/linked_data/getty_aat_ld4l_cache.json
- config/authorities/linked_data/getty_tgn_ld4l_cache.json
- config/authorities/linked_data/getty_ulan_ld4l_cache.json
- config/authorities/linked_data/locdemographics_ld4l_cache.json
- config/authorities/linked_data/locgenres_ld4l_cache.json
- config/authorities/linked_data/locnames_ld4l_cache.json
- config/authorities/linked_data/locperformance_ld4l_cache.json
- config/authorities/linked_data/locsubjects_ld4l_cache.json
- config/authorities/linked_data/mesh_ld4l_cache.json
- config/authorities/linked_data/nalt_cornell.json
- config/authorities/linked_data/nalt_ld4l_cache.json
- config/authorities/linked_data/oclcfast_direct.json
- config/authorities/linked_data/oclcfast_ld4l_cache.json
- config/authorities/linked_data/sharevde_cornell_instance_ld4l_cache.json
- config/authorities/linked_data/sharevde_cornell_work_ld4l_cache.json
- config/authorities/linked_data/sharevde_stanford_instance_ld4l_cache.json
- config/authorities/linked_data/sharevde_stanford_work_ld4l_cache.json
- config/authorities/linked_data/sharevde_ucsd_instance_ld4l_cache.json
- config/authorities/linked_data/sharevde_ucsd_work_ld4l_cache.json
Fixes https://github.com/LD4P/qa_server/issues/93
> add `encode: true` to search query param for all 2.0 configs

- config/authorities/linked_data/locgenres_ld4l_cache.json
- config/authorities/linked_data/scenarios/locgenres_ld4l_cache_validation.yml
Addresses QA changes for Issue https://github.com/LD4P/qa_server/issues/50
> update extended configuration of LCGFT to match spreadsheet

- config/authorities/linked_data/locgenres_ld4l_cache.json
- config/authorities/linked_data/locsubjects_ld4l_cache.json
REF:  https://github.com/LD4P/qa_server/issues/116, https://github.com/LD4P/qa_server/issues/143
Also...
* adds startRecord parameter to LCSH with default 1
* updated startRecord default to 1 for LCGFT
> add extended context to LCSH

- config/authorities/linked_data/locdemographics_ld4l_cache.json
- config/authorities/linked_data/locsubjects_ld4l_cache.json
- config/authorities/linked_data/scenarios/locdemographics_ld4l_cache_validation.yml
Also…
* adds startRecord
* fix copy/paste error in lcgft i18n keys
> add extended context to lcdgt

- config/authorities/linked_data/scenarios/sharevde_stanford_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_ucdavis_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_ucsd_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_yale_ld4l_cache_validation.yml
- config/authorities/linked_data/sharevde_cornell_ld4l_cache.json
- config/authorities/linked_data/sharevde_cuboulder_ld4l_cache.json
- config/authorities/linked_data/sharevde_duke_ld4l_cache.json
- config/authorities/linked_data/sharevde_frick_ld4l_cache.json
- config/authorities/linked_data/sharevde_stanford_ld4l_cache.json
- config/authorities/linked_data/sharevde_ucdavis_ld4l_cache.json
- config/authorities/linked_data/sharevde_ucsd_ld4l_cache.json
- config/authorities/linked_data/sharevde_yale_ld4l_cache.json
Also, add startRecord parameter for all other sharevde configs.
> add sharevde configs for stanford, ucdavis, ucsd, yale

- app/authorities/qa/authorities/wikidata.rb
- app/authorities/qa/authorities/wikidata/generic_authority.rb
- app/prepends/prepended_presenters/authority_list_presenter.rb
- config/application.rb
- config/authorities/linked_data/scenarios/wikidata_direct_validation.yml
- config/authorities/linked_data/wikidata_direct.json
sample URLs on Authorities tab
added sample URLs for Discogs too
Observations:
* search is fast - very little data is returned
* fetch is really slow (> 30s) - tons of unused data returned; unable to find a way to limit data to a single language
> basic wikidata access

- Gemfile.lock
- config/application.rb
- db/migrate/20190816015610_create_performance_history.qa_server.rb
- db/schema.rb
includes:
* performance metrics
* fetch term via the UI
> update to qa_server 2.2.0

- config/authorities/linked_data/scenarios/sharevde_chicago_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_cuboulder_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_duke_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_frick_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_harvard_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_michigan_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_minnesota_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_nlm_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_northwestern_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_princeton_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_texasam_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_ucsd_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_upenn_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_uwashington_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/sharevde_yale_ld4l_cache_validation.yml
- config/authorities/linked_data/sharevde_chicago_ld4l_cache.json
- config/authorities/linked_data/sharevde_harvard_ld4l_cache.json
- config/authorities/linked_data/sharevde_michigan_ld4l_cache.json
- config/authorities/linked_data/sharevde_minnesota_ld4l_cache.json
- config/authorities/linked_data/sharevde_nlm_ld4l_cache.json
- config/authorities/linked_data/sharevde_northwestern_ld4l_cache.json
- config/authorities/linked_data/sharevde_princeton_ld4l_cache.json
- config/authorities/linked_data/sharevde_texasam_ld4l_cache.json
- config/authorities/linked_data/sharevde_upenn_ld4l_cache.json
- config/authorities/linked_data/sharevde_uwashington_ld4l_cache.json
* add config and validation for chicago, michigan, minnesota, nlm, northwestern, princeton, texas a&m, u penn, u washington
* add term tests for work, superwork, and instance for all sharevde
* Harry Ransom connection to cache isn’t working, so that authority config is pending
> add remaining sharevde configs

- config/authorities/linked_data/geonames_ld4l_cache.json
Effects fields...
* Parent
* Parent2
* Parent Country
> expand parent URIs to labels in extended context for GEONAMES

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- config/locales/qa_server.en.yml
includes update of qa_server 2.2.3 bug release
> prep for release to master

- CHANGELOG.md
- app/authorities/qa/authorities/wikidata/generic_authority.rb
- config/locales/qa_server.en.yml
minor tweak to make wikidata values an array
> prep release 4.0.1

- CHANGELOG.md
- Gemfile.lock
- config/locales/qa_server.en.yml
* update to samvera/qa 5.1.1
* add response header which has pagination information for search and summary info for fetch
> update to qa 5.1.0 with search pagination info

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/authorities/qa/authorities/wikidata/generic_authority.rb
- config/locales/qa_server.en.yml
> update to include response_header in search results

- CHANGELOG.md
- config/locales/qa_server.en.yml
* disable nalt_cornell authority
> prep for release

- CHANGELOG.md
- config/locales/qa_server.en.yml
* update to LD4P/qa_server 5.0.3
* bug fix - use correct parameters for search query
> prep for 4.4.1 release

- CHANGELOG.md
- config/locales/qa_server.en.yml
* add configuration for database pool size
* update puma dependency
> prep for release 4.5.0

- CHANGELOG.md
- Gemfile.lock
- config/database.yml
- config/locales/qa_server.en.yml
* add configuration for database pool size
* update puma dependency
> release 4.5.0

- config/initializers/qa.rb
> release 4.7.3 - turn ip logging back on

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- config/locales/qa_server.en.yml
* update to LD4P/qa_server 5.5.0
* use caching with expiry for all data for the monitor status page
> update qa_server to 5.5.0 and re-release 4.7.4

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- config/locales/qa_server.en.yml
* update to LD4P/qa_server 5.5.0
* use caching with expiry for all data on monitor status page
> release 4.7.5

- config/authorities/linked_data/ligatus_ld4l_cache.json
- config/authorities/linked_data/scenarios/ligatus_ld4l_cache_validation.yml
Extended context defined based on the spread sheet…
https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=393177076
> add config for new authority ligatus

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- config/initializers/qa_server.rb
- config/locales/qa_server.en.yml
* add subauthorities for MeSH
* update to LD4P/qa_server v7.0.0
* refactor of caching system to simplify the process
* rename monitor_cache_service to cache_expiry_service
* move generation of hourly graph to cache_processors
* move generation of daily and monthly graphs to cache_processors
* move performance datatable cache control to cache_processors
* move caching of summary and historical data to cache_processors
* move caching of test execution marker to cache_processors
* move performance cache of performance data to cache_processors
> release v5.1.0

- CHANGELOG.md
- config/initializers/qa_server.rb
- config/locales/qa_server.en.yml
turn off all graphs since they aren’t working
> release 5.2.0.rc7

- CHANGELOG.md
- Gemfile.lock
- config/locales/qa_server.en.yml
* update to LD4P/qa_server v7.1.3
* bug fix for performance datatable never displays
> release 5.2.4 - update to qa_server 7.1.3

- .ebextensions/upgrade_bundler.config
- CHANGELOG.md
- Gemfile.lock
- config/authorities/linked_data/cerl_ld4l_cache.json
- config/locales/qa_server.en.yml
* fix cerl ct prefix to end with /
* update to LD4P/qa_server v7.1.3
* bug fix for performance datatable never displays
> release 5.2.4

- CHANGELOG.md
- config/initializers/qa_server.rb
- config/locales/qa_server.en.yml
* test new location of graphs in public directory by generating the history graph
> display history graph

- CHANGELOG.md
- Gemfile.lock
- config/locales/qa_server.en.yml
* fix graph fails generation when any label is empty string
> release 5.3.2.rc4 - fix empty label for graphs

- config/locales/qa_server.en.yml
* generate the performance graphs
* setup background jobs in all environments
* update to LD4P/qa_server v7.2.1
* fix graph fails generation when any label is empty string
> release 5.3.2 - full release

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- config/locales/qa_server.en.yml
* update to LD4P/qa_server v7.4.0
* add size and complexity performance statistics (not auto-generated)
> release v5.5.0 - update to qa_server 7.4.0

- config/authorities/linked_data/oclcfast_ld4l_cache.json
- config/authorities/linked_data/scenarios/agrovoc_direct_validation.yml
- config/authorities/linked_data/scenarios/agrovoc_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/dbpedia_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/geonames_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/getty_aat_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/getty_tgn_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/getty_ulan_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/ligatus_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/locdemographics_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/locgenres_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/locnames_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/locnames_rwo_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/mesh_nlm_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/nalt_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/oclcfast_ld4l_cache_validation.yml
- config/authorities/linked_data/scenarios/rda_registry_ld4l_cache_validation.yml
Add accuracy tests primarily for subauthority coverage.
> sync authority validations with updates for subauths

- CHANGELOG.md
- config/locales/qa_server.en.yml
* update to Samvera/QA 5.5.0
* fixes change of LOC API URLs from http to https
* update to Rails 5.2
* update related dependencies
> release 5.6.0

- config/authorities/property_attribute.yml
- config/authorities/property_type.yml
Requested for use in Sinopia.
Searching:
* https://lookup.ld4l.org/authorities/search/local/property_type?q=nest
* https://lookup.ld4l.org/authorities/search/local/property_attribute?q=required
List all terms:
* https://lookup.ld4l.org/authorities/terms/local/property_type
* https://lookup.ld4l.org/authorities/terms/local/property_attribute
> add local subauths for property attributes and types

- config/authorities/linked_data/scenarios/rda_registry_ld4l_cache_validation.yml
Need to check and see if term fetch should be supported.
> fix syntax error in rda_registry; temporarily remove term fetch test

- CHANGELOG.md
- Gemfile.lock
- config/locales/qa_server.en.yml
Update to LD4P/qa_server 7.7.1
* Bug fix: fix background colors in historical uptime table
> release v6.1.1

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- config/locales/qa_server.en.yml
Update LD4P/qa_server to v7.8.0
* dogear expected and actual cells when accuracy test is pending
> release v6.2.0 - dogear pending accuracy tests

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- config/authorities/linked_data/scenarios/mesh_nlm_ld4l_cache_validation.yml
- config/locales/qa_server.en.yml
Update to LD4P/qa_server 7.8.0
* dogear expected and actual cells when accuracy test is pending
> release v6.2.0 - dogear pending tests

- CHANGELOG.md
- config/locales/qa_server.en.yml
* update swagger api doc to include local and module authorities
> release v6.4.1

- CHANGELOG.md
- config/locales/qa_server.en.yml
* add authority LOCCULTURAL_ORGANIZATIONS_LD4L_CACHE
* fix duplicates in publisher cities
> release v6.6.2

- config/authorities/linked_data/ntsf_direct.json
- config/authorities/linked_data/scenarios/ntsf_direct_validation.yml
Fixes https://github.com/LD4P/qa_server/issues/481
> Add Norwegian thesaurus on genre and form

- CHANGELOG.md
- config/locales/qa_server.en.yml
* add authority BIBBI
* add authority NTSF (Norwegian Thesaurus)
* add authority Homosaurus
> release v6.7.3

- CHANGELOG.md
- config/locales/qa_server.en.yml
* add authority Humord
* fix config and validation for authority NTSF (Norwegian Thesaurus for Genre/Form)
> release v6.7.4
