Gemfile.lock
config/authorities/linked_data/scenarios/locgenres_ld4l_cache_validation.yml

* update to use latest commit to min_context branch of QA which brings in numeric sort
* `Case books` returns 0 results from ld4l cache and id.loc.gov.  Changed to `Casebooks` which has the expected subject uri as the first result

add numeric sort; fix typo in accuracy test

---

Gemfile
Gemfile.lock
config/environments/integration.rb

Show stacktrace and command line in the browser instead of the Something Went Wrong modal when error occur in integration.  This will allow for easier debugging on AWS on the integration machine.

show stack trace when errors occur in integration

---

.gitignore
Gemfile
Gemfile.lock
config/initializers/qa_server.rb
public/qa/apidoc/apidoc.json
public/qa/apidoc/index.html

API DOC changes
* include link to API DOC in main nav menu
* change Go Back link to Home link
* fix server selection variables
* add production server to servers list and set to default
Other changes
* update ld4p/qa_server to 1.1.0
* shows status history as datatable instead of graph

Add link to API Doc in main nav menu

---

config/authorities/linked_data/scenarios/sharevde_cornell_work_ld4l_cache_validation.yml

Getting data for The Golden Notebook takes too long and times out the tests.  It is not a good connection test.  28M of data are returned by this query.

remove golden notebook from cornell sharevde tests

---

config/authorities/linked_data/scenarios/sharevde_frick_work_ld4l_cache_validation.yml
config/authorities/linked_data/sharevde_frick_work_ld4l_cache.json

This is the latest release by ShareVDE which uses BibFrame2 ontology.

add config to sharevde data for Frick

---

app/authorities/qa/authorities/wikidata/generic_authority.rb
app/prepends/prepended_presenters/authority_list_presenter.rb
config/authorities/linked_data/DISABLED/scenarios/mesh_bioportal_ld4l_cache_validation.yml

* wikidata - include label in extended context (same as what linked data module does by convention through configurations)
* discogs - action in authority list was set to search when it was fetching a term
* bioportal - was validating with an nih URI instead of a bioportal URI

minor tweaks to wikidata, discogs, and bioportal mesh

---

config/authorities/linked_data/scenarios/locnames_rwo_ld4l_cache_validation.yml

There is no data returned for ‘golden notebook’, but there is for ‘twain’.

fix failing test for LCNAF RWO title subauth

---

CHANGELOG.md
Gemfile
Gemfile.lock
config/locales/qa_server.en.yml

4.0.2 was supposed to do this, but the prepend for LD4P/qa_server did not pass through the response header.  Release 5.0.0 of LD4P/qa_server, part of this release, does retain the response header in the results.l

release 4.0.3 to include response header

---

CHANGELOG.md
Gemfile
Gemfile.lock
config/locales/qa_server.en.yml

* update to LD4P/qa_server 5.2.1
* set monitoring to expire nightly at 3am ET by default
* save performance data once a day when running monitoring tests
* update to Samvera/QA 5.3.0
* add a request id to the search and find request headers
* log exception for graph load failures
* optionally include IP info at start of search/find linked data requests
* update Puma to 4.3.1

Release/4.7.0 - update to qa 5.3 and qa_server 5.2.1

---

CHANGELOG.md
config/database.yml
config/initializers/qa.rb
config/initializers/qa_server.rb
config/locales/qa_server.en.yml

qa_server 5.2.1 brings in caching of performance test results, so it is no longer a performance issue itself from all the database writes.
* update config initializers to no longer suppress performance data
* truncate error messages written to the database instead of raising an exception

do not suppress performance testing & prep for release 4.7.1

---

config/authorities/linked_data/scenarios/geonames_direct_validation.yml

geonames switched to use https with their URIs instead of http.  This means that the extraction process that depended on the subject URI matching the requested URI failed to find any metadata matching the ldpaths.
Consideration:
Should QA be able to find data in the graph using either/both http and https versions of the requested URI?

update geonames scenario to fetch URI using https instead of http

---

CHANGELOG.md
Gemfile
Gemfile.lock
config/environments/development.rb
config/initializers/qa_server.rb
config/locales/qa_server.en.yml
db/migrate/20200218125146_add_date_column_to_scenario_run_history.qa_server.rb
db/schema.rb

* add extended context for [MeSH](https://id.nlm.nih.gov/mesh/) authority
* add authority [Ligatus](https://www.ligatus.org.uk/lob/)
* add authority [CERL](https://www.cerl.org/)
* update to LD4P/qa_server v6.2.0
* use authentication for refreshing monitor tests
* add performance cache logger
* exceeding max performance cache size flushing the cache
* change historical summary to show number of days instead of number of tests (original intent)

prep release 5.0.0

---

CHANGELOG.md
Gemfile.lock
config/initializers/qa_server.rb
config/locales/qa_server.en.yml

* writes out performance cache at end of monitor tests run
* attempt to display history graph (should gracefully display nothing if it is not able to create the graph)

update qa_server to 7.1.1; attempt display graph

---

config/locales/qa_server.en.yml

* update to LD4P/qa_server v7.1.1
* fix: empty performance cache after running monitor status tests
* includes changes from LD4P/qa_server v7.1.0
* allow performance cache size to be set by environment variable
* move generation of history graph to cache_processors
* log warning in monitor logger if graphs fail to create
* monitor_status page won't try to display graphs if graph file does not exist

release 5.2.0

---

CHANGELOG.md
config/initializers/qa_server.rb
config/locales/qa_server.en.yml

* remove hardcoded max_performance_cache_size so the value is picked up from ENV

release 5.2.1 - max_performance_cache_size from ENV

---

CHANGELOG.md
Gemfile.lock
config/locales/qa_server.en.yml

* update to LD4P/qa_server v7.1.2
* make configs that return true/false end with ?
* add tests for configs that weren’t tested
* fix bugs in config#convert_size_to_bytes in response to testing

release 5.2.2 - update to qa_server 7.1.2

---

CHANGELOG.md
Gemfile
Gemfile.lock
config/locales/qa_server.en.yml

* update to LD4P/qa_server v7.2.0
* move generated monitor status graphs from assets to public directory

release 5.3.0 - update qa_server to 7.2.0

---

.ebextensions/upgrade_bundler.config
.gitignore
CHANGELOG.md
Gemfile
Gemfile.lock
config/authorities/linked_data/cerl_ld4l_cache.json
config/environments/development.rb
config/environments/integration.rb
config/environments/production.rb
config/environments/staging.rb
config/initializers/qa_server.rb
config/locales/qa_server.en.yml

* generate the performance graphs
* setup background jobs in all environments
* update to LD4P/qa_server v7.2.1
* fix graph fails generation when any label is empty string
* test new location of graphs in public directory by generating the history graph
* update to LD4P/qa_server v7.2.0
* move generated monitor status graphs from assets to public directory

release 5.3.2 - graphs working on AWS

---

config/authorities/linked_data/oclcfast_direct.json

According to OCLC, eventName entity is being split.  A new entity 'meeting' will be added.  They stated that most events are actually meetings.  It is unclear that eventName will continue once this process is complete.  There was a question locally asking the question whether something like WWII would be treated as a meeting instead of an event.

add meeting subauth to oclcfast_direct

---

config/authorities/linked_data/scenarios/oclc_fast_validation.yml
config/authorities/linked_data/scenarios/oclcfast_direct_validation.yml

OCLC moved most events to be meetings.  As part of this move, the linked data search results only return `rdf:type Meeting` even if the term has `rdf:type Event Name`.
For now, tests are being disabled.
Issue https://github.com/LD4P/qa_server/issues/327 records the need to revisit this as the linked data at OCLC continues to evolve.

Remove failing tests as they are due to changes at OCLC

---

config/authorities/linked_data/locvocabs_ld4l_cache.json
config/authorities/linked_data/scenarios/locvocabs_ld4l_cache_validation.yml

At least temporarily, removing access to fetch terms for locvocab in the second commit.
Working to determine if support for term fetch is a requirement.  It is not currently supported by the cache for the LOC small vocabularies.

add loc small vocabularies

---

config/authorities/linked_data/locvocabs_ld4l_cache.json
config/authorities/linked_data/scenarios/getty_ulan_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/mesh_nlm_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/oclcfast_ld4l_cache_validation.yml

Fixes...
* new getty_ulan test that returns less than 200 chars (never worked)
* new oclcfast test that returns less than 200 chars (never worked)
* temporarily removes Email test for MeSH - needs indexing of entry terms
* temporarily points new locvocabs to cache staging server pending updates to other authorities

Fix broken tests

---

config/authorities/linked_data/getty_aat_ld4l_cache.json
config/authorities/linked_data/getty_tgn_ld4l_cache.json
config/authorities/linked_data/locdemographics_new_ld4l_cache.json
config/authorities/linked_data/locgenres_new_ld4l_cache.json
config/authorities/linked_data/locnames_new_ld4l_cache.json
config/authorities/linked_data/locnames_new_rwo_ld4l_cache.json
config/authorities/linked_data/locperformance_new_ld4l_cache.json
config/authorities/linked_data/locsubjects_new_ld4l_cache.json
config/authorities/linked_data/scenarios/dbpedia_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/locdemographics_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/locdemographics_new_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/locgenres_new_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/locnames_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/locnames_new_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/locnames_new_rwo_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/locnames_rwo_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/locperformance_new_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/locsubjects_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/locsubjects_new_ld4l_cache_validation.yml

update authorities
* add authority configs for LOC using the new indexing approach (auth name match: loc*_new_ld4l_cache)
* sync auth configs with changes made in LD4P/qa_server
* add extended context definitions for getty aat and tgn

update and sync authority definitions: loc, getty, and a few others

---

CHANGELOG.md
config/authorities/linked_data/scenarios/cerl_new_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/getty_tgn_new_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/locgenres_new_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/locnames_new_ld4l_cache_validation.yml
config/locales/qa_server.en.yml

* add 48 small LOC vocabs (e.g. carriers, content_types, etc)
* add extended context for getty aat and tgn
* fix validations where results are returned but are too small
* sync auth configs and validations with ld4p/qa_server templates
* temporarily add new_cache auths testing new indexing scheme
Also, syncs old and new validations so the new ones have the latest fixes.

release 5.8.0

---

config/authorities/linked_data/scenarios/geonames_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/getty_ulan_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/locnames_ld4l_cache_validation.yml
config/authorities/linked_data/scenarios/oclcfast_ld4l_cache_validation.yml

* geonames - New York City
* getty_ulan - URIs end in `-agent` to match RWO URI
* locnames - fix URI expected for Camden NJ
* oclcfast - loosen expectations on Scream

tweak validation tests

---

config/authorities/linked_data/locnames_rwo2_new_ld4l_cache.json
config/authorities/linked_data/locnames_rwo3_new_ld4l_cache.json
config/authorities/linked_data/locnames_rwo_new_ld4l_cache.json
config/authorities/linked_data/scenarios/locnames_rwo3_new_ld4l_cache_validation.yml

May need to change this based on preferred resolution for [LD4P/qa_server Issue #421](https://github.com/LD4P/qa_server/issues/421).  For now, this restores the display of the primary label.

use madsrdf:authoritativeLabel for prefLabel

---

config/authorities/linked_data/getty_tgn_ld4l_cache.json
config/authorities/linked_data/getty_tgn_new_ld4l_cache.json
config/authorities/linked_data/getty_ulan_ld4l_cache.json
config/authorities/linked_data/getty_ulan_new_ld4l_cache.json

* fixes the ldpath for label in both TGN and ULAN
* fixes getty and skosxl prefixes in both
* adds context for ULAN
* expands context for TGN
* sets id to the subjectURI in the results
NOTE: id should be `dc:identifier`, but that predicate is not in the search results.  
See issues:
* [#419](https://github.com/LD4P/qa_server/issues/419) - Getty TGN blank id and label in primary result data (new indexing)
* [#420](https://github.com/LD4P/qa_server/issues/420) - Getty ULAN blank id and label in primary result data (new indexing)

fix id and label for Getty TGN and ULAN

---

CHANGELOG.md
Gemfile
Gemfile.lock
config/locales/qa_server.en.yml

* update to qa_server v7.6.0 - allows for use of Rails 6
* sync authority configs and validations with definitions in LD4P/qa_server
* many updates to configs and validations based on changes for new indexing approach
* update to Rails 5.2.5 to fix mimemagic gem yank
* update dependencies

release 6.0.0 - support new indexing approach

---

CHANGELOG.md
Gemfile.lock
config/locales/qa_server.en.yml

* update to LD4P/qa_server 7.7.0
* remove unused translations
* show notification when refreshing starts on monitor status page
* hide data in Authority Connection History for non-active authorities
* loosen threshold for caution in historical uptime table
* minor tweaks missed in original sync

release v6.1.0 - UI improvement for Monitor Status page

---

CHANGELOG.md
Gemfile
Gemfile.lock
config/locales/qa_server.en.yml

Update to LD4P/qa_server 7.7.0 - Primarily adds UI improvements on Monitor Status page.
* remove unused translations
* show notification when refreshing starts on monitor status page
* hide data in Authority Connection History for non-active authorities
* loosen threshold for caution in historical uptime table
* minor tweaks missed in original sync

release v6.1.0 - UI improvements on Monitor Status page

---

CHANGELOG.md
Gemfile.lock
config/locales/qa_server.en.yml

Update to LD4P/qa_server 7.7.1
* Bug fix:  fix background colors in historical uptime table

release v6.1.1 - bug fix in LD4P/qa_server 7.7.1

---

CHANGELOG.md
config/authorities/linked_data/scenarios/mesh_nlm_ld4l_cache_validation.yml
config/locales/qa_server.en.yml

Release v6.1.3
* adds geographic subauth for MeSH-NLM
* updates Spain test to search geographic subauth for MeSH

release 6.1.3 - update Spain test to search geographic subauth for MeSH

---

CHANGELOG.md
Gemfile.lock
config/locales/qa_server.en.yml

* Add chart showing simulated graph (in table) of the last 30 days of up-down connection data

release 6.3.0 - up-down connection chart

---

config/authorities/linked_data/isni_ld4l_cache.json
config/authorities/linked_data/isni_ld4l_wrapper.json
config/authorities/linked_data/scenarios/isni_ld4l_wrapper_validation.yml

Renames existing `ISNI_LD4L_CACHE` to `ISNI_LD4L_WRAPPED`.  This reflects the fact that this service, although coming from the cache server, is in reality a wrap of a direct call to the ISNI API.
The `ISNI_LD4L_CACHE` authority name is now being used for an actual cache of an RDF download provided by ISNI.

add cached ISNI with context

---

Gemfile
Gemfile.lock

Reverts cul-it/qa_server#335
Prior to #335, nokogiri was pinned to '< 1.13' which requires ruby '> 2.5'.
qa_server does not use the reported vulnerability, so reinstating the pin until ruby can be updated.

Revert "Bump nokogiri from 1.12.5 to 1.13.2"
